name: Send Discord Notification on Pull Request

on:
  pull_request:
    types: [opened, closed]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: Ilshidur/action-discord@v1.0.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          message: "Новий Pull Request створено!"
